export interface ProviderConfig {
  id: string
  name: string
  category: ProviderCategory
  description: string
  website: string
  docsUrl: string
  fields: ProviderField[]
  icon?: string
}

export interface ProviderField {
  key: string
  label: string
  type: 'text' | 'password' | 'url'
  placeholder: string
  required: boolean
}

export type ProviderCategory =
  | 'llm'
  | 'image'
  | 'video'
  | 'voice'
  | 'telephony'
  | 'email'
  | 'automation'
  | 'messaging'
  | 'google'
  | 'crm'
  | 'developer'
  | 'custom'

export const PROVIDER_CATEGORIES: Record<ProviderCategory, { label: string; description: string }> = {
  llm: { label: 'LLM Providers', description: 'Large Language Models for text generation and reasoning' },
  image: { label: 'Image Generation', description: 'AI-powered image creation and editing' },
  video: { label: 'Video Generation', description: 'AI video creation and editing platforms' },
  voice: { label: 'Voice AI & Speech', description: 'Voice synthesis, cloning, transcription, and phone agents' },
  telephony: { label: 'Telephony & SMS', description: 'Phone calls, SMS, and communication infrastructure' },
  email: { label: 'Email Services', description: 'Email delivery and inbox management' },
  automation: { label: 'Automation Platforms', description: 'Workflow automation and integration platforms' },
  messaging: { label: 'Messaging & Chat', description: 'Chat platforms and customer communication' },
  google: { label: 'Google Workspace', description: 'Google productivity and analytics tools' },
  crm: { label: 'CRM & Business Tools', description: 'Customer relationship and project management' },
  developer: { label: 'Developer Platforms', description: 'Code, cloud, and infrastructure services' },
  custom: { label: 'Custom API', description: 'Connect any app or service with a REST API' },
}

const apiKeyField = (placeholder: string): ProviderField => ({
  key: 'apiKey',
  label: 'API Key',
  type: 'password',
  placeholder,
  required: true,
})

const webhookField: ProviderField = {
  key: 'webhookUrl',
  label: 'Webhook URL',
  type: 'url',
  placeholder: 'https://...',
  required: true,
}

export const ALL_PROVIDERS: ProviderConfig[] = [
  // ─── LLM Providers ────────────────────────────────────────
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'llm',
    description: 'GPT-4o, GPT-4 Turbo, o1, o3, DALL-E',
    website: 'https://openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    fields: [apiKeyField('sk-...')],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'llm',
    description: 'Claude 4, Claude 3.5 Sonnet, Haiku',
    website: 'https://anthropic.com',
    docsUrl: 'https://docs.anthropic.com',
    fields: [apiKeyField('sk-ant-...')],
  },
  {
    id: 'google',
    name: 'Google AI',
    category: 'llm',
    description: 'Gemini 2.0, Gemini Pro, PaLM',
    website: 'https://ai.google.dev',
    docsUrl: 'https://ai.google.dev/docs',
    fields: [apiKeyField('AIza...')],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'llm',
    description: 'DeepSeek V3, DeepSeek R1',
    website: 'https://deepseek.com',
    docsUrl: 'https://platform.deepseek.com/docs',
    fields: [apiKeyField('sk-...')],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'llm',
    description: 'Mistral Large, Medium, Codestral',
    website: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'llm',
    description: 'Command R+, Embed, Rerank',
    website: 'https://cohere.com',
    docsUrl: 'https://docs.cohere.com',
    fields: [apiKeyField('...')],
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'llm',
    description: 'Ultra-fast LLM inference (LPU)',
    website: 'https://groq.com',
    docsUrl: 'https://console.groq.com/docs',
    fields: [apiKeyField('gsk_...')],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'llm',
    description: 'Sonar models with real-time search',
    website: 'https://perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    fields: [apiKeyField('pplx-...')],
  },
  {
    id: 'together',
    name: 'Together AI',
    category: 'llm',
    description: 'Open-source model hosting (Llama, Mixtral)',
    website: 'https://together.ai',
    docsUrl: 'https://docs.together.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'llm',
    description: 'Fast inference for open models',
    website: 'https://fireworks.ai',
    docsUrl: 'https://docs.fireworks.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'qwen',
    name: 'Alibaba Qwen',
    category: 'llm',
    description: 'Qwen 2.5, multilingual LLM',
    website: 'https://qwen.ai',
    docsUrl: 'https://help.aliyun.com/zh/model-studio',
    fields: [apiKeyField('...')],
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    category: 'llm',
    description: 'GLM-4.6, Chinese-optimized LLM',
    website: 'https://open.bigmodel.cn',
    docsUrl: 'https://open.bigmodel.cn/dev/api',
    fields: [apiKeyField('...')],
  },
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    category: 'llm',
    description: 'Kimi K2, long-context specialist',
    website: 'https://moonshot.cn',
    docsUrl: 'https://platform.moonshot.cn/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    category: 'llm',
    description: 'MiniMax models, multimodal',
    website: 'https://minimax.chat',
    docsUrl: 'https://api.minimax.chat/document',
    fields: [apiKeyField('...')],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    category: 'llm',
    description: 'Grok models by xAI',
    website: 'https://x.ai',
    docsUrl: 'https://docs.x.ai',
    fields: [apiKeyField('xai-...')],
  },

  // ─── Image Generation ─────────────────────────────────────
  {
    id: 'dalle',
    name: 'OpenAI DALL-E',
    category: 'image',
    description: 'DALL-E 3 image generation (uses OpenAI key)',
    website: 'https://openai.com/dall-e-3',
    docsUrl: 'https://platform.openai.com/docs/guides/images',
    fields: [apiKeyField('sk-...')],
  },
  {
    id: 'stability',
    name: 'Stability AI',
    category: 'image',
    description: 'Stable Diffusion, SDXL, SD3',
    website: 'https://stability.ai',
    docsUrl: 'https://platform.stability.ai/docs',
    fields: [apiKeyField('sk-...')],
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'image',
    description: 'Premium AI image generation',
    website: 'https://midjourney.com',
    docsUrl: 'https://docs.midjourney.com',
    fields: [apiKeyField('...')],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'image',
    description: 'Run open-source ML models (Flux, SDXL)',
    website: 'https://replicate.com',
    docsUrl: 'https://replicate.com/docs',
    fields: [apiKeyField('r8_...')],
  },
  {
    id: 'fal',
    name: 'Fal.ai',
    category: 'image',
    description: 'Fast image generation APIs',
    website: 'https://fal.ai',
    docsUrl: 'https://fal.ai/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'leonardo',
    name: 'Leonardo AI',
    category: 'image',
    description: 'Creative AI image generation',
    website: 'https://leonardo.ai',
    docsUrl: 'https://docs.leonardo.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    category: 'image',
    description: 'Text-in-image specialist',
    website: 'https://ideogram.ai',
    docsUrl: 'https://developer.ideogram.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'flux',
    name: 'Flux (Black Forest Labs)',
    category: 'image',
    description: 'Flux Pro, Dev, Schnell models',
    website: 'https://blackforestlabs.ai',
    docsUrl: 'https://docs.bfl.ml',
    fields: [apiKeyField('...')],
  },
  {
    id: 'adobe_firefly',
    name: 'Adobe Firefly',
    category: 'image',
    description: 'Adobe creative AI generation',
    website: 'https://firefly.adobe.com',
    docsUrl: 'https://developer.adobe.com/firefly-api',
    fields: [apiKeyField('...')],
  },
  {
    id: 'clipdrop',
    name: 'Clipdrop',
    category: 'image',
    description: 'Image editing and generation by Stability',
    website: 'https://clipdrop.co',
    docsUrl: 'https://clipdrop.co/apis',
    fields: [apiKeyField('...')],
  },

  // ─── Video Generation ─────────────────────────────────────
  {
    id: 'kling',
    name: 'Kling AI',
    category: 'video',
    description: 'Kling 3.0, 15s video, lip-sync',
    website: 'https://klingai.com',
    docsUrl: 'https://www.klingapi.com',
    fields: [apiKeyField('...')],
  },
  {
    id: 'runway',
    name: 'Runway',
    category: 'video',
    description: 'Gen-3 Alpha video generation',
    website: 'https://runway.ml',
    docsUrl: 'https://docs.runwayml.com',
    fields: [apiKeyField('...')],
  },
  {
    id: 'pika',
    name: 'Pika Labs',
    category: 'video',
    description: 'Creative video generation',
    website: 'https://pika.art',
    docsUrl: 'https://docs.pika.art',
    fields: [apiKeyField('...')],
  },
  {
    id: 'luma',
    name: 'Luma AI',
    category: 'video',
    description: 'Dream Machine, 3D and video',
    website: 'https://lumalabs.ai',
    docsUrl: 'https://docs.lumalabs.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'hailuo',
    name: 'HaiLuo AI',
    category: 'video',
    description: 'MiniMax Video generation',
    website: 'https://hailuoai.video',
    docsUrl: 'https://hailuoai.video/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'wan',
    name: 'Wan AI (Vidu)',
    category: 'video',
    description: 'Chinese video generation model',
    website: 'https://www.vidu.io',
    docsUrl: 'https://www.vidu.io/docs',
    fields: [apiKeyField('...')],
  },

  // ─── Voice AI & Phone Agents ──────────────────────────────
  {
    id: 'vapi',
    name: 'VAPI',
    category: 'voice',
    description: 'Build voice AI agents for phone calls',
    website: 'https://vapi.ai',
    docsUrl: 'https://docs.vapi.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'bland',
    name: 'Bland AI',
    category: 'voice',
    description: 'AI phone call automation',
    website: 'https://bland.ai',
    docsUrl: 'https://docs.bland.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'retell',
    name: 'Retell AI',
    category: 'voice',
    description: 'Conversational voice agents',
    website: 'https://retellai.com',
    docsUrl: 'https://docs.retellai.com',
    fields: [apiKeyField('...')],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'voice',
    description: 'Voice synthesis, cloning, agents',
    website: 'https://elevenlabs.io',
    docsUrl: 'https://docs.elevenlabs.io',
    fields: [apiKeyField('...')],
  },
  {
    id: 'playht',
    name: 'PlayHT',
    category: 'voice',
    description: 'Voice cloning and TTS',
    website: 'https://play.ht',
    docsUrl: 'https://docs.play.ht',
    fields: [apiKeyField('...'), { key: 'userId', label: 'User ID', type: 'text', placeholder: 'Your PlayHT User ID', required: true }],
  },
  {
    id: 'deepgram',
    name: 'Deepgram',
    category: 'voice',
    description: 'Speech-to-text, real-time transcription',
    website: 'https://deepgram.com',
    docsUrl: 'https://developers.deepgram.com',
    fields: [apiKeyField('...')],
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI',
    category: 'voice',
    description: 'Transcription, summarization, sentiment',
    website: 'https://assemblyai.com',
    docsUrl: 'https://www.assemblyai.com/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'resemble',
    name: 'Resemble AI',
    category: 'voice',
    description: 'Voice cloning and speech generation',
    website: 'https://resemble.ai',
    docsUrl: 'https://docs.resemble.ai',
    fields: [apiKeyField('...')],
  },
  {
    id: 'murf',
    name: 'Murf AI',
    category: 'voice',
    description: 'Text-to-speech with AI voices',
    website: 'https://murf.ai',
    docsUrl: 'https://murf.ai/api',
    fields: [apiKeyField('...')],
  },
  {
    id: 'whisper',
    name: 'Whisper (OpenAI)',
    category: 'voice',
    description: 'Speech-to-text via OpenAI (uses OpenAI key)',
    website: 'https://openai.com/research/whisper',
    docsUrl: 'https://platform.openai.com/docs/guides/speech-to-text',
    fields: [apiKeyField('sk-...')],
  },

  // ─── Telephony & SMS ──────────────────────────────────────
  {
    id: 'twilio',
    name: 'Twilio',
    category: 'telephony',
    description: 'Voice, SMS, WhatsApp, Video',
    website: 'https://twilio.com',
    docsUrl: 'https://www.twilio.com/docs',
    fields: [
      { key: 'accountSid', label: 'Account SID', type: 'text', placeholder: 'AC...', required: true },
      { key: 'apiKey', label: 'Auth Token', type: 'password', placeholder: '...', required: true },
    ],
  },
  {
    id: 'vonage',
    name: 'Vonage / Nexmo',
    category: 'telephony',
    description: 'Voice, SMS, messaging APIs',
    website: 'https://vonage.com',
    docsUrl: 'https://developer.vonage.com',
    fields: [apiKeyField('...'), { key: 'apiSecret', label: 'API Secret', type: 'password', placeholder: '...', required: true }],
  },
  {
    id: 'plivo',
    name: 'Plivo',
    category: 'telephony',
    description: 'Cloud voice and SMS',
    website: 'https://plivo.com',
    docsUrl: 'https://www.plivo.com/docs',
    fields: [{ key: 'authId', label: 'Auth ID', type: 'text', placeholder: '...', required: true }, { key: 'apiKey', label: 'Auth Token', type: 'password', placeholder: '...', required: true }],
  },
  {
    id: 'telnyx',
    name: 'Telnyx',
    category: 'telephony',
    description: 'Voice, SMS, fax APIs',
    website: 'https://telnyx.com',
    docsUrl: 'https://developers.telnyx.com',
    fields: [apiKeyField('KEY...')],
  },
  {
    id: 'messagebird',
    name: 'MessageBird',
    category: 'telephony',
    description: 'Omnichannel communication',
    website: 'https://messagebird.com',
    docsUrl: 'https://developers.messagebird.com',
    fields: [apiKeyField('...')],
  },

  // ─── Email Services ───────────────────────────────────────
  {
    id: 'sendgrid',
    name: 'SendGrid',
    category: 'email',
    description: 'Transactional and marketing email',
    website: 'https://sendgrid.com',
    docsUrl: 'https://docs.sendgrid.com',
    fields: [apiKeyField('SG...')],
  },
  {
    id: 'mailgun',
    name: 'Mailgun',
    category: 'email',
    description: 'Email delivery API',
    website: 'https://mailgun.com',
    docsUrl: 'https://documentation.mailgun.com',
    fields: [apiKeyField('...'), { key: 'domain', label: 'Domain', type: 'text', placeholder: 'mg.yourdomain.com', required: true }],
  },
  {
    id: 'gmail',
    name: 'Gmail API',
    category: 'email',
    description: 'Send and read Gmail programmatically',
    website: 'https://gmail.google.com',
    docsUrl: 'https://developers.google.com/gmail/api',
    fields: [apiKeyField('OAuth token or service account key')],
  },
  {
    id: 'outlook',
    name: 'Microsoft Outlook',
    category: 'email',
    description: 'Outlook mail and calendar API',
    website: 'https://outlook.com',
    docsUrl: 'https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview',
    fields: [apiKeyField('Bearer token')],
  },
  {
    id: 'ses',
    name: 'Amazon SES',
    category: 'email',
    description: 'AWS Simple Email Service',
    website: 'https://aws.amazon.com/ses',
    docsUrl: 'https://docs.aws.amazon.com/ses',
    fields: [
      { key: 'accessKeyId', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...', required: true },
      { key: 'apiKey', label: 'Secret Access Key', type: 'password', placeholder: '...', required: true },
      { key: 'region', label: 'Region', type: 'text', placeholder: 'us-east-1', required: true },
    ],
  },

  // ─── Automation Platforms ─────────────────────────────────
  {
    id: 'n8n',
    name: 'n8n',
    category: 'automation',
    description: 'Open-source workflow automation',
    website: 'https://n8n.io',
    docsUrl: 'https://docs.n8n.io',
    fields: [webhookField, apiKeyField('n8n API key (optional)')],
  },
  {
    id: 'make',
    name: 'Make.com',
    category: 'automation',
    description: 'Visual automation platform (formerly Integromat)',
    website: 'https://make.com',
    docsUrl: 'https://www.make.com/en/api-documentation',
    fields: [apiKeyField('...')],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'automation',
    description: 'Connect 6000+ apps with automations',
    website: 'https://zapier.com',
    docsUrl: 'https://platform.zapier.com/docs',
    fields: [webhookField],
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    category: 'automation',
    description: 'Developer-first integration platform',
    website: 'https://pipedream.com',
    docsUrl: 'https://pipedream.com/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'activepieces',
    name: 'Activepieces',
    category: 'automation',
    description: 'Open-source automation alternative',
    website: 'https://activepieces.com',
    docsUrl: 'https://www.activepieces.com/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'pabbly',
    name: 'Pabbly Connect',
    category: 'automation',
    description: 'Affordable automation platform',
    website: 'https://pabbly.com',
    docsUrl: 'https://www.pabbly.com/connect/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'power_automate',
    name: 'Power Automate',
    category: 'automation',
    description: 'Microsoft workflow automation',
    website: 'https://powerautomate.microsoft.com',
    docsUrl: 'https://learn.microsoft.com/en-us/power-automate',
    fields: [apiKeyField('Bearer token')],
  },

  // ─── Messaging & Chat ─────────────────────────────────────
  {
    id: 'slack',
    name: 'Slack',
    category: 'messaging',
    description: 'Team messaging and bot integration',
    website: 'https://slack.com',
    docsUrl: 'https://api.slack.com/docs',
    fields: [{ key: 'apiKey', label: 'Bot Token', type: 'password', placeholder: 'xoxb-...', required: true }, webhookField],
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'messaging',
    description: 'Community messaging and bots',
    website: 'https://discord.com',
    docsUrl: 'https://discord.com/developers/docs',
    fields: [{ key: 'apiKey', label: 'Bot Token', type: 'password', placeholder: '...', required: true }],
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    category: 'messaging',
    description: 'WhatsApp messaging API',
    website: 'https://business.whatsapp.com',
    docsUrl: 'https://developers.facebook.com/docs/whatsapp',
    fields: [apiKeyField('Bearer token'), { key: 'phoneNumberId', label: 'Phone Number ID', type: 'text', placeholder: '...', required: true }],
  },
  {
    id: 'telegram',
    name: 'Telegram Bot',
    category: 'messaging',
    description: 'Telegram bot messaging API',
    website: 'https://telegram.org',
    docsUrl: 'https://core.telegram.org/bots/api',
    fields: [{ key: 'apiKey', label: 'Bot Token', type: 'password', placeholder: '123456:ABC-DEF...', required: true }],
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'messaging',
    description: 'Teams messaging and webhook integration',
    website: 'https://teams.microsoft.com',
    docsUrl: 'https://learn.microsoft.com/en-us/microsoftteams/platform',
    fields: [webhookField],
  },
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'messaging',
    description: 'Customer messaging platform',
    website: 'https://intercom.com',
    docsUrl: 'https://developers.intercom.com',
    fields: [apiKeyField('...')],
  },
  {
    id: 'crisp',
    name: 'Crisp',
    category: 'messaging',
    description: 'Customer support chat platform',
    website: 'https://crisp.chat',
    docsUrl: 'https://docs.crisp.chat/api',
    fields: [apiKeyField('...')],
  },
  {
    id: 'drift',
    name: 'Drift',
    category: 'messaging',
    description: 'Conversational marketing platform',
    website: 'https://drift.com',
    docsUrl: 'https://devdocs.drift.com',
    fields: [apiKeyField('...')],
  },

  // ─── Google Workspace ─────────────────────────────────────
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    category: 'google',
    description: 'Schedule and manage events',
    website: 'https://calendar.google.com',
    docsUrl: 'https://developers.google.com/calendar',
    fields: [apiKeyField('OAuth token or service account key')],
  },
  {
    id: 'google_sheets',
    name: 'Google Sheets',
    category: 'google',
    description: 'Read and write spreadsheets',
    website: 'https://sheets.google.com',
    docsUrl: 'https://developers.google.com/sheets/api',
    fields: [apiKeyField('OAuth token or service account key')],
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    category: 'google',
    description: 'File storage and management',
    website: 'https://drive.google.com',
    docsUrl: 'https://developers.google.com/drive',
    fields: [apiKeyField('OAuth token or service account key')],
  },
  {
    id: 'google_docs',
    name: 'Google Docs',
    category: 'google',
    description: 'Document creation and editing',
    website: 'https://docs.google.com',
    docsUrl: 'https://developers.google.com/docs',
    fields: [apiKeyField('OAuth token or service account key')],
  },
  {
    id: 'google_meet',
    name: 'Google Meet',
    category: 'google',
    description: 'Video conferencing API',
    website: 'https://meet.google.com',
    docsUrl: 'https://developers.google.com/meet',
    fields: [apiKeyField('OAuth token or service account key')],
  },
  {
    id: 'google_analytics',
    name: 'Google Analytics',
    category: 'google',
    description: 'Website and app analytics',
    website: 'https://analytics.google.com',
    docsUrl: 'https://developers.google.com/analytics',
    fields: [apiKeyField('OAuth token or service account key')],
  },

  // ─── CRM & Business Tools ────────────────────────────────
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'crm',
    description: 'Enterprise CRM platform',
    website: 'https://salesforce.com',
    docsUrl: 'https://developer.salesforce.com/docs',
    fields: [apiKeyField('Bearer token'), { key: 'instanceUrl', label: 'Instance URL', type: 'url', placeholder: 'https://yourorg.salesforce.com', required: true }],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'crm',
    description: 'CRM, marketing, and sales platform',
    website: 'https://hubspot.com',
    docsUrl: 'https://developers.hubspot.com',
    fields: [apiKeyField('pat-...')],
  },
  {
    id: 'zoho',
    name: 'Zoho CRM',
    category: 'crm',
    description: 'Business apps and CRM suite',
    website: 'https://zoho.com/crm',
    docsUrl: 'https://www.zoho.com/crm/developer',
    fields: [apiKeyField('...')],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'crm',
    description: 'Spreadsheet-database hybrid',
    website: 'https://airtable.com',
    docsUrl: 'https://airtable.com/developers/web/api',
    fields: [apiKeyField('pat...')],
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'crm',
    description: 'Workspace, docs, and databases',
    website: 'https://notion.so',
    docsUrl: 'https://developers.notion.com',
    fields: [apiKeyField('ntn_...')],
  },
  {
    id: 'monday',
    name: 'Monday.com',
    category: 'crm',
    description: 'Project and work management',
    website: 'https://monday.com',
    docsUrl: 'https://developer.monday.com',
    fields: [apiKeyField('...')],
  },

  // ─── Developer Platforms ──────────────────────────────────
  {
    id: 'github',
    name: 'GitHub',
    category: 'developer',
    description: 'Code hosting and CI/CD',
    website: 'https://github.com',
    docsUrl: 'https://docs.github.com/en/rest',
    fields: [{ key: 'apiKey', label: 'Personal Access Token', type: 'password', placeholder: 'ghp_...', required: true }],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'developer',
    description: 'DevOps platform and code hosting',
    website: 'https://gitlab.com',
    docsUrl: 'https://docs.gitlab.com/ee/api',
    fields: [{ key: 'apiKey', label: 'Access Token', type: 'password', placeholder: 'glpat-...', required: true }],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'developer',
    description: 'Open-source Firebase alternative',
    website: 'https://supabase.com',
    docsUrl: 'https://supabase.com/docs',
    fields: [apiKeyField('...'), { key: 'projectUrl', label: 'Project URL', type: 'url', placeholder: 'https://xxx.supabase.co', required: true }],
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'developer',
    description: 'Google app development platform',
    website: 'https://firebase.google.com',
    docsUrl: 'https://firebase.google.com/docs',
    fields: [apiKeyField('...')],
  },
  {
    id: 'aws',
    name: 'AWS',
    category: 'developer',
    description: 'Amazon Web Services cloud platform',
    website: 'https://aws.amazon.com',
    docsUrl: 'https://docs.aws.amazon.com',
    fields: [
      { key: 'accessKeyId', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...', required: true },
      { key: 'apiKey', label: 'Secret Access Key', type: 'password', placeholder: '...', required: true },
      { key: 'region', label: 'Region', type: 'text', placeholder: 'us-east-1', required: true },
    ],
  },

  // ─── Custom API ───────────────────────────────────────────
  {
    id: 'custom_api',
    name: 'Custom API',
    category: 'custom',
    description: 'Connect any REST API — provide base URL, API key, and headers',
    website: '',
    docsUrl: '',
    fields: [
      { key: 'appName', label: 'App Name', type: 'text', placeholder: 'My Custom App', required: true },
      { key: 'baseUrl', label: 'Base URL', type: 'url', placeholder: 'https://api.yourapp.com/v1', required: true },
      { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Your API key', required: true },
      { key: 'authHeader', label: 'Auth Header Name', type: 'text', placeholder: 'Authorization (default)', required: false },
      { key: 'customHeaders', label: 'Custom Headers (JSON)', type: 'text', placeholder: '{"X-Custom": "value"}', required: false },
    ],
  },
]

export function getProvidersByCategory(category: ProviderCategory): ProviderConfig[] {
  return ALL_PROVIDERS.filter((p) => p.category === category)
}

export function getProviderById(id: string): ProviderConfig | undefined {
  return ALL_PROVIDERS.find((p) => p.id === id)
}

export function getAllProviderIds(): string[] {
  return ALL_PROVIDERS.map((p) => p.id)
}
